spring.application.name=journal-service
server.port=8083

spring.datasource.url=jdbc:mysql://journal-db:3306/journal_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka

management.tracing.sampling.probability=1.0
